Create usersStore and postsStore
Yuliya-Lukashova/RTK_Table pull request #1
Opened 2024-01-31 13:46 UTC by Yuliya-Lukashova

Added a store

2024-01-31 14:27 UTC, s-skubedin requested changes
Исправляй замечания по всему проекту

2024-01-31 14:27 UTC, s-skubedin commented on src/store/api.ts
> +export default api;
Пустая строка в конце файла

2024-01-31 14:27 UTC, s-skubedin commented on src/store/api.ts
> +const api = axios.create({ baseURL: "https://dummyjson.com/" });
api должно быть в env

2024-01-31 14:27 UTC, s-skubedin commented on src/store/index.ts
> +import usersSlice  from '../store/users/usersStore';
експортируй reducer

2024-01-31 14:27 UTC, s-skubedin commented on src/store/posts/postsStore.ts
именуй файлы в стиле kebab-case

2024-01-31 14:27 UTC, s-skubedin commented on src/store/posts/postsThunks.ts
> +);
пустая строка в конце файла

2024-01-31 14:27 UTC, s-skubedin commented on src/store/posts/postsStore.ts
> +  },
Нет кейса обработки ошибки

2024-01-31 14:27 UTC, s-skubedin commented on src/store/posts/postsThunks.ts
> +      if (err instanceof AxiosError) console.log(err.message);
нет обработки else

2024-02-05 09:33 UTC, Yuliya-Lukashova commented on src/store/api.ts
> +export default api;
done

2024-02-05 09:33 UTC, Yuliya-Lukashova commented on src/store/api.ts
> +const api = axios.create({ baseURL: "https://dummyjson.com/" });
done

2024-02-05 09:33 UTC, Yuliya-Lukashova commented on src/store/index.ts
> +import usersSlice  from '../store/users/usersStore';
done

2024-02-05 09:33 UTC, Yuliya-Lukashova commented on src/store/posts/postsStore.ts
done

2024-02-05 09:33 UTC, Yuliya-Lukashova commented on src/store/posts/postsThunks.ts
> +);
done

2024-02-05 09:33 UTC, Yuliya-Lukashova commented on src/store/posts/postsStore.ts
> +  },
done

2024-02-05 09:33 UTC, Yuliya-Lukashova commented on src/store/posts/postsThunks.ts
> +      if (err instanceof AxiosError) console.log(err.message);
done

2024-02-05 09:41 UTC, s-skubedin requested changes

2024-02-05 09:41 UTC, s-skubedin commented on src/store/posts/posts-store.ts
> +      state.postsError = action.error.message;
Нет обработки на else

2024-02-05 09:41 UTC, s-skubedin commented on src/store/posts/posts-thunks.ts
> +    }
А RTK отлавливает эту ошибку? Как будто это работать не будет

2024-02-05 11:58 UTC, Yuliya-Lukashova commented on src/store/posts/posts-thunks.ts
> +    }
исправила

2024-02-05 12:43 UTC, Yuliya-Lukashova commented on src/store/posts/posts-store.ts
> +      state.postsError = action.error.message;
done

2024-02-05 14:53 UTC, merged